version: "3.8"

# Defining the services
services:
  # Client / Frontend service
  client:
    # Path for frontend image relative to docker-compose file
    build: ./
    # image: shumaslaghari/job-hunt-client:latest
    # Ports to bind
    # '{exposed_port}:{internal_port}'
    stdin_open: true
    tty: true
    ports:
      - "80:80"


